- README.md
- opentracing/__init__.py
- opentracing/harness/api_check.py
- opentracing/propagation.py
- opentracing/tracer.py
- tests/test_noop_span.py
Per https://github.com/opentracing/opentracing.github.io/issues/70, we are getting rid of injector()/extractor() and the respective classes/interfaces in favor of Tracer.inject() and Tracer.join().
> Remove the Injector/Extractor layer

- README.md
- opentracing/__init__.py
- opentracing/harness/api_check.py
- opentracing/propagation.py
- tests/test_noop_span.py
@yurishkuro curious what you think about this... I realize we just went through the exercise of moving to interface-only carriers in https://github.com/opentracing/basictracer-go/pull/15, but for some reason it felt too heavy-handed comment-wise in Python. I guess it's a tradeoff between flexibility and comprehensibility (and perhaps I'm more concerned about the latter).
(C.f.: https://github.com/opentracing/opentracing.github.io/issues/73)
> Simple carriers for Python

- opentracing/span.py
- tests/test_utils.py
The OpenTracing spec specifies that baggage keys should match a
specified regex and be case insensitive. By adding a method to the
package to canonicalize keys, we can ensure that all OpenTracing
implementations have a consistent way of meeting the spec.
Per https://github.com/opentracing/opentracing-python/issues/22
Pardon my python, it's fairly rusty.
> Add method to canonicalize baggage keys

- opentracing/__init__.py
- opentracing/harness/api_check.py
- opentracing/propagation.py
- opentracing/tracer.py
- tests/test_noop_span.py
- tests/test_noop_tracer.py
Also:
- rename `span_context` to `referee` in Reference
- document expected behavior when `referee=None`
> Rename ChildOf/FollowsFrom to child_of/follows_from

- opentracing/propagation.py
- opentracing/tracer.py
Also, update .py to use a `child_of` param instead of overloading `references` as before.
> Add an HTTP_HEADERS format

- CHANGELOG.rst
- opentracing/harness/api_check.py
- opentracing/span.py
- tests/test_api.py
- tests/test_api_check_mixin.py
Per opentracing/opentracing.github.io#106
cc @bensigelman
> Move set/get_baggage back to Span; add SpanContext.baggage

- opentracing/span.py
Since this is a deprecated method, the main task should be to translate to log_kv rather than blindly pass through.
cc @yurishkuro
> Add a better default log() impl

- README.rst
Sorry for spamming... this *should* fix the README rst code block.
> New line after `code-block` so RST can render properly

- setup.py
The source code doesn't use anything provided by the 'futures' module.
Signed-off-by: Nehal J Wani <nehaljw.kkd1@gmail.com>
> Remove 'futures' from install_requires

- README.rst
- docs/api.rst
- opentracing/__init__.py
- opentracing/harness/api_check.py
- opentracing/scope.py
- opentracing/scope_manager.py
- opentracing/tracer.py
- tests/test_api.py
- tests/test_api_check_mixin.py
- tests/test_scope.py
- tests/test_scope_manager.py
This is an updated PR for supporting `Span` propagation, sitting on top of @palazzem's effort (#63), and updated with the feedback received there, as well as updated with the latest Java API.
Summary of changes:
* `Tracer.start_manual` was removed.
* `Tracer.start_span` stays, without being deprecated, but **now** by default sets the active `Span` as the parent one, if any. This is a breaking change, and passing `ignore_active_span=True` will get the previous behavior.
* `Tracer.start_active` became `Tracer.start_active_span` (longer, but better, more complete name overall).
* `finish_on_close` became non-optional, being only left as optional in `start_active_span` as `False` (as _all_ its parameters are optional, even `operation_name`).
* Added `Scope.manager`, similar to `Span.tracer` …
> Implement ScopeManager for in-process propagation (updated)

- opentracing/ext/scope.py
- opentracing/ext/scope_manager.py
- opentracing/mocktracer/tracer.py
- tests/ext/test_scope.py
- tests/ext/test_scope_manager.py
This includes ThreadLocalScopeManager in the `ext`
submodule.
Wondering if we should import `ThreadLocalScopeManager` by default, so instead of
```python
from opentracing.ext.scope_manager import ThreadLocalScopeManager
```
we do:
```python
from opentracing.ext import ThreadLocalScopeManager
```
@yurishkuro @palazzem
> Update MockTracer to use the Scopes API.

- CHANGELOG.rst
- docs/conf.py
- opentracing/ext/scope.py
- opentracing/propagation.py
- opentracing/scope.py
- opentracing/scope_manager.py
- opentracing/span.py
- opentracing/tracer.py
Building (and reading through) the documentation revealed a number of issues:
```
...opentracing.Tracer.start_active_span:8: WARNING: Definition list ends without a blank line; unexpected unindent.
...opentracing.Tracer.start_active_span:16: WARNING: Block quote ends without a blank line; unexpected unindent.
...opentracing.Tracer.start_active_span:18: WARNING: Definition list ends without a blank line; unexpected unindent.
../CHANGELOG.rst:30: WARNING: Inline strong start-string without end-string.
../CHANGELOG.rst:118: WARNING: Bullet list ends without a blank line; unexpected unindent.
...
copying static files... WARNING: html_static_path entry u'/Users/kyle.verhoog/dev/ot-py-kyle/docs/_static' does not exist
...
build succeeded, 6 warnings.
```
This PR fixes these warnings.
This PR …
> Fix some v2.0.0 docs

- docs/api.rst
- opentracing/mocktracer/tracer.py
- opentracing/scope.py
- opentracing/tracer.py
Minor documentation improvement pass:
* Few minor fixes.
* MockTracer documentation & inclusion in the produced API docs.
@yurishkuro
> Add proper documentation for MockTracer.

- README.rst
Added integration with the published API in ReadTheDocs.
* Currently using https://opentracing-python.readthedocs.io (from my personal account - can grant access to anyone who requests it).
* Currently it points by default to the last published version (1.3.0)
* Left the 1.3.0 available for-ever, in case somebody wants to see how the API worked pre-`ScopeManager` integration ;)
* Left the v2.0.0 version there, to preview what we will publish upon the 2.0 release - will remove afterwards.
@palazzem @yurishkuro @pglombardo
> Add a ReadTheDocs banner to the README

- opentracing/harness/api_check.py
This pull request fixes an unclosed active scope in tests. Not closing it leads to failures in other tests while using `ThreadLocalScopeManager` and possibly other scope managers.
> fix unclosed active scope in tests

- opentracing/scope_managers/tornado.py
> Fix typo in tornado scope manager documentation

- opentracing/scope.py
- opentracing/span.py
- tests/test_noop_span.py
- tests/test_scope.py
Would address #72 
cc @yurishkuro @palazzem
> Better error handling in context managers for Span/Scope.

- setup.py
Setting the `pytest-cov` to 2.6.0, as 2.6.1 changes its dependency from `pytest` 2.x to 3.x (!?).
This should get our builds back to green (recent ones such as #109 were failing because of this).
@yurishkuro @opentracing/opentracing-python-maintainers
> Use pytest-cov==2.6.0 as 2.6.1 depends on pytest>=3.6.0

- opentracing/__init__.py
- tests/test_globaltracer.py
Adds support for knowing if a global tracer has been registered via a global variable including tests.
NOTE: Python currently does not prevent you re-registering a global tracer multiple times like C# and Java does.
> Add support for indicating if a global tracer has been registered

- .travis.yml
- README.rst
- opentracing/propagation.py
- opentracing/span.py
- opentracing/tracer.py
- setup.py
- tox.ini
Hello,
As a software engineer, I'd like to have support for modern versions of Python declared in `setup.py` and to have corresponding tests on CI.
Also, I'd like to be able to conveniently run tests in my local environment, so I want to add a `tox` config file.
These changes:
- Add Python 3.5 and 3.7 to `setup.py`
- Add Python 3.5, 3.7, and 3.8-dev to `.travis.yml`
- Add `tox.ini`
- Add a mention of `tox` into `Development` section of `README`
- Pin `tornado` at the tests requriements to `<6`
- Simplify the tests requirements
- Fix `flake8` warnings (for the latest version of `flake8`)
> Add support for Python 3.5/3.7 and fix tests

- opentracing/scope.py
- opentracing/span.py
- tests/test_scope.py
Hello,
Technically, a scope could contain `None` as a span, but on exit it calls `_on_error` on a span with no check.
Currently, this issue affects `opentracing_instrumentation` library:
https://travis-ci.org/uber-common/opentracing-python-instrumentation/jobs/525712144#L530-L616
These changes:
- Make the `_on_error` method static
- Add a check for a span to the `_on_error` method
cc @carlosalberto
~**Note:** Error for Python 3.6 on CI was expected and it's not related to these changes.~
> Fix __exit__ method of Scope class

- README.rst
`opentracing.ScopeManager.active` is a property, therefore, we should not add brackets when it is accessed
> Fix typo in README.rst: opentracing.ScopeManager.active is a property not a method

- opentracing/harness/api_check.py
- opentracing/harness/scope_check.py
- setup.py
- tests/test_globaltracer.py
- tests/test_noop_span.py
- tests/test_scope.py
This is an attempt to fix #142.
> Do not use mock (the PyPI backport library) when possible

- README.rst
Need to pass in span.context rather than span
> fix(readme): Inject code example (#1)
